# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rlambert <rlambert@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2014/11/03 11:25:08 by rlambert          #+#    #+#              #
#    Updated: 2015/11/12 18:15:47 by rlambert         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = a.out


all: $(NAME)

$(NAME):
	gcc main.c

clean:
	rm a.out

fclean: clean

re: fclean all

.PHONY: all clean fclean re
